name: GitHub Action Example
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
        working-directory: ./api
    steps:
      # master branch로 변경합니다.
      - name: Checkout master
        uses: actions/checkout@master

      # node_modules를 매번 설치하면 비효율적이므로 캐시로 저장해둡니다.
      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ./api/node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-

      # npm 패키지들을 설치합니다.
      - name: Install dependencies
        working-directory: ./api
        run: npm install

      # Docker Image를 자동으로 build하고 push합니다.
      # Docker Hub ID와 PW는 GitHub settings에 있는 secrets에 저장해둡니다.
      # [Your DockerHub ID]/[Your Repository Name] 예시) dal96k/woomin-facebook
      - name: Docker image build and push
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_ID }}
          password: ${{ secrets.DOCKER_PW }}
          repository: baayoo71/catppingmall
          tags: 1.0

      # Docker Hub에 새로운 Image가 push 완료되면 CodeDeploy Agent가 동작되도록 합니다.
      # --application-name과 --deployment-group-name은 아까 작성하신 애플리케이션 이름과 그룹 이름으로 대체하시면 됩니다.
      # [Your GitHub Repository] 예시) Woomin-Jeon/facebook-clone-server
      # "commitId=${GITHUB_SHA}" 코드가 자동으로 최신 commit을 불러옵니다.
      # 아까 보관해두었던 AWS_ACCESS_KEY_ID와 AWS_SECRET_ACCESS_KEY는 GitHub secrets에 저장해둡니다.
      - name: Trigger the CodeDeploy in EC2 instance
        working-directory: ./api
        run: aws deploy --region ap-northeast-2 create-deployment --application-name CodeDeploy-application-catppingmall --deployment-config-name CodeDeployDefault.OneAtATime --deployment-group-name CodeDeploy-group-catppingmall --github-location repository=lygggg/cat-web,commitId=${GITHUB_SHA}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          Default_region_name: ap-northeast-2