name: catppingmall
on: 
  push:                               # master Branch에서 push 이벤트가 일어났을 때만 실행
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-18.04
    env:
      working-directory: ./frontend-react
    steps:
      - name: Checkout source code.   # 레포지토리 체크아웃
        uses: actions/checkout@master
        working-directory: ./frontend-react

      - name: Cache node modules      # node modules 캐싱
        uses: actions/cache@v1
        working-directory: ./frontend-react
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
          

      - name: Install Dependencies    # 의존 파일 설치
        working-directory: ./frontend-react
        run: npm install

      - name: Build
        working-directory: ./frontend-react
        run: npm run build

      - name: Deploy                  # S3에 배포하기
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        working-directory: ./frontend-react
        run: |
          aws s3 cp \
            --recursive \
            --region ap-northeast-2 \
            build s3://catppingmall